// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function $$new(ns) {
  return "app:" + ns + ":" + String(Date.now());
}

var Uri = {
  $$new: $$new,
};

var cmp = Caml_obj.compare;

var Uri_comparable = Belt_Id.MakeComparable({
  cmp: cmp,
});

function now(param) {
  return Date.now();
}

var DateTime = {
  now: now,
};

function string(x) {
  return /* String */ {
    _0: x,
  };
}

var Value = {
  string: string,
};

var Fact = {};

var Entity = {};

function $$new$1(param) {
  return Belt_Map.make(Uri_comparable);
}

var EntityTable = {
  $$new: $$new$1,
};

function $$new$2(param) {
  return {
    facts: [],
    entities: Belt_Map.make(Uri_comparable),
  };
}

function state(db, fact) {
  db.facts.push(fact);
  return db;
}

var DB = {
  $$new: $$new$2,
  state: state,
};

export { DateTime, DB, Entity, EntityTable, Fact, Uri, Uri_comparable, Value };
/* Uri_comparable Not a pure module */
